version: '3.5'

services:
  data_warehouse:
    container_name: data_warehouse_psql
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
