version: '3.5'

services:
  data_warehouse:
    container_name: data_warehouse
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
      - "8081"
    restart: unless-stopped

  etl:
    container_name: etl_scripts
    build: .
    env_file:
      - .env
    depends_on:
      - data_warehouse
    ports:
      - "8081:8081"
    expose:
      - "5432"
      - "8081"
    restart: always
    volumes:
      - /logs:/logs
