version: '3.5'

services:
  data_warehouse:
    container_name: data_warehouse
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
      - "8081"
    restart: unless-stopped
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    container_name: etl_scripts
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    expose:
      - "5432"
      - "8081"
    restart: always
    volumes:
      - /logs:/logs
    links:
      - data_warehouse
    depends_on:
      data_warehouse:
        condition: service_healthy
